<div id="hauptrolle__toolbox">
    <div id="hauptrolle__toogle">
        <span>T</span>
    </div>
    <div class="toolbox__section toolbox__layout-handles">
        <?php $layoutArray = $this->getLayout()->getUpdate()->getHandles(); ?>
        <ul>
            <li>Layout Handles</li>
            <?php foreach ($layoutArray as $handle => $handleValue): ?>
                <li><?php echo $handleValue; ?></li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="toolbox__section toolbox_theme">
        <ul>
            <li>Design</li>
            <li>Package: <?php echo Mage::getDesign()->getPackageName(); ?></li>
            <li>Locale: <?php echo Mage::getDesign()->getTheme('locale') ?></li>
            <li>Layout: <?php echo Mage::getDesign()->getTheme('layout') ?></li>
            <li>Template: <?php echo Mage::getDesign()->getTheme('template') ?></li>
            <li>Skin: <?php echo Mage::getDesign()->getTheme('skin') ?></li>
            <li>jQuery: <span id="jquery-loaded"></span></li>
            <li>Module: <?php echo Mage::app()->getFrontController()->getRequest()->getModuleName(); ?></li>
            <li>Action: <?php echo $this->getRequest()->getActionName(); ?></li>
            <li>Controller: <?php echo $this->getRequest()->getControllerName(); ?></li>
        </ul>
    </div>
    <div class="toolbox__section toolbox_store-info">
        <ul>
            <li>Store Informations</li>
            <li>Store Id: <?php echo Mage::app()->getStore()->getStoreId(); ?></li>
            <li>Store Name: <?php echo Mage::app()->getStore()->getName(); ?></li>
        </ul>
    </div>
    <div class="toolbox__section toolbox_stuff">
        <ul>
            <li><a href="<?php Mage::getUrl('') ?>toolbox/index/clearcache">Clear Cache</a></li>
            <li><a href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/index/index'); ?>" target="blank">Goto Backend</a></li>
            <?php /*
            <?php $route = Mage::app()->getRequest()->getRouteName(); ?>
            <?php if($route == "cms"): ?>
                <?php $pageId = Mage::getBlockSingleton('cms/page')->getPage()->getId(); ?>
                <li><a target="_blank" href="<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/cms_page/edit', array('page_id' => $pageId)) ?>">Edit CMS Page</a></li>
            <?php endif; ?>
            */ ?>
            <li><a href="<?php echo Mage::getUrl('') ?>toolbox/tool/toggletemplatehints">Toggle Tempalte Hints</a></li>
        </ul>
    </div>
</div>